Upgrade to 3.10 with static pods
Before upgrading the control plane, ensure that bootstrapping and other
cluster level operations like installing openshift-sdn and the config
sync plugin have completed. Then upgrade the masters to use
bootstrapping mode one-by-one and have the kubelet take over running the
master components as static pods.

When transitioning each node, move the existing node-config.yaml to
bootstrap-node-config.yaml to allow node config sync to take over if
necessary. Also ensure that the node group config is properly configured
for bootstrapping as v3.9 did not always ensure that config was correct.

diff --git a/roles/openshift_node_group/files/sync.yaml b/roles/openshift_node_group/files/sync.yaml
--- a/roles/openshift_node_group/files/sync.yaml
+++ b/roles/openshift_node_group/files/sync.yaml
@@ -102,10 +102,17 @@ spec:
             ) &
             break
           done
+<<<<<<< HEAD
           mkdir -p /etc/origin/node/tmp
           # periodically refresh both node-config.yaml and relabel the node
           while true; do
             if ! oc extract "configmaps/${name}" -n openshift-node --to=/etc/origin/node/tmp --confirm --request-timeout=10s --config /etc/origin/node/node.kubeconfig "--token=$( cat /var/run/secrets/kubernetes.io/serviceaccount/token )"  > /dev/null; then
+=======
+
+          # periodically refresh both node-config.yaml and relabel the node
+          while true; do
+            if ! oc extract "configmaps/${name}" -n openshift-node --to=/etc/origin/node --confirm --request-timeout=10s --config /etc/origin/node/node.kubeconfig "--token=$( cat /var/run/secrets/kubernetes.io/serviceaccount/token )"  > /dev/null; then
+>>>>>>> Upgrade to 3.10 with static pods
               echo "error: Unable to retrieve latest config for node" 2>&1
               sleep 15 &
               wait $!
@@ -138,10 +145,15 @@ spec:
                   fi
                 fi
               else
+<<<<<<< HEAD
                 echo "error: The downloaded node configuration is invalid, retrying later" 2>&1
                 sleep 10 &
                 wait $!
                 continue
+=======
+                echo "error: The downloaded node configuration is invalid, exiting" 2>&1
+                exit 1
+>>>>>>> Upgrade to 3.10 with static pods
               fi
               if ! pkill -U 0 -f '(^|/)hyperkube kubelet '; then
                 echo "error: Unable to restart Kubelet" 2>&1
@@ -190,6 +202,7 @@ spec:
       - name: host-sysconfig-node
         hostPath:
           path: /etc/sysconfig
+<<<<<<< HEAD
       - hostPath:
           path: /var/run/dbus
         name: var-run-dbus
@@ -199,3 +212,5 @@ spec:
       # Sync daemonset should tolerate all taints to make sure it runs on all nodes
       tolerations:
       - operator: "Exists"
+=======
+>>>>>>> Upgrade to 3.10 with static pods
